name: Build PPA source packages
on:
  - push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - focal
          - jammy
          - kinetic
    runs-on: ubuntu-20.04
    steps:
    - name: Clone the repositories
      run: |
          git clone https://github.com/canonical/go-dqlite
          git clone https://github.com/canonical/dqlite-ppa -b go-dqlite --depth 1

    - name: Setup dependencies
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq debhelper devscripts dh-golang

    - name: Build source package
      env:
        DEBFULLNAME: "Github Actions"
        DEBEMAIL: "noreply@linuxcontainers.org"
        TARGET: ${{ matrix.target }}
      run: |
          cp -R dqlite-ppa/debian go-dqlite/
          cd go-dqlite/
          go mod vendor
          VERSION="$(git describe --tags | sed -e "s/^v//" -e "s/-/+git/")"
          dch --create \
            --distribution ${TARGET} \
            --package go-dqlite \
            --newversion ${VERSION}~${TARGET}1 \
            "Automatic build from Github"
          debuild -S -sa -us -uc -d

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debian-${{ matrix.target }}
        if-no-files-found: error
        path: |
          *.buildinfo
          *.changes
          *.dsc
          *.tar.*
